site_name: Chris Jennings - his Notes
site_description: My personal digital garden
site_author: ""
site_url: https://notes.chrisjennings.net
copyright: Copyright &copy; 2023 Chris Jennings
repo_url: https://github.com/Pageboy/pageboy.github.io
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/pageboy
    - icon: fontawesome/brands/instagram 
      link: https://instagram.com/pagebuoy
features:
  - navigation.indexes
extra_css:
  - stylesheets/extra.css
  - stylesheets/glightbox.min.css
extra_javascript:
  - javascripts/glightbox.min.js

theme:
    name: 'material'
    palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    font:
      text: Sen
      code: Roboto Mono   



   
# Extensions
markdown_extensions:
  - meta
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: false
      use_pygments: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences 

  # - attr_list
  # - pymdownx.arithmatex
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  # - pymdownx.tasklist:
  #     custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - admonition
  - toc:
      permalink: false

plugins:
  - search
  - roamlinks
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      auto_caption: true
      caption_position: bottom
